name = "tos-api"
main = "worker.js"
compatibility_date = "2024-09-24"

[env.production]
name = "tos-api-prod"

[env.staging]
name = "tos-api-staging"

# 환경 변수
[vars]
NODE_ENV = "production"
API_VERSION = "1.0.0"

# 데이터베이스 설정 (실제 값은 Cloudflare 대시보드에서 설정)
# DB_MASTER_HOST = "your-db-host"
# DB_MASTER_PORT = "3306"
# DB_MASTER_USER = "your-username"
# DB_MASTER_PASSWORD = "your-password"
# DB_NAME = "tos_db"

# R2 버킷 설정
# R2_BASE_URL = "https://your-r2-bucket.com"

# CORS 설정
# CORS_ORIGIN = "https://your-frontend-domain.com"
